const fs = require("fs");
const faker = require("faker");

// Set locale to use English
faker.locale = "en";

// random data
(() => {
  const db = {
    categories: [
      { id: 0, name: "Phones" },
      { id: 1, name: "Laptops" },
      { id: 2, name: "Tablets" },
      { id: 3, name: "Watches" },
    ],
    phoneTypes: [
      { id: 0, name: "Iphone", country: "USA" },
      { id: 1, name: "Xiao Mi", country: "China" },
      { id: 2, name: "Sam Sung", country: "Korea" },
      { id: 3, name: "Oppo", country: "China" },
      { id: 4, name: "Vivo", country: "China" },
    ],
    products: [
      {
        id: 1,
        categoriesId: 0,
        name: "Iphone 12",
        phoneTypesId: 0,
        colors: { name: "Xanh dương", value: "#64b5f6" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/213031/iphone-12-violet-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "IOS",
        salePrices: 3400,
        promotionPercents: 15,
        ram: "64GB",
        originalPrices: 4000,
      },
      {
        id: 2,
        categoriesId: 0,
        name: "Iphone 12 Pro Max",
        phoneTypesId: 0,
        colors: { name: "Đỏ", value: "#ef5350" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-xanh-duong-new-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "IOS",
        salePrices: 720,
        promotionPercents: 20,
        ram: "64GB",
        originalPrices: 900,
      },
      {
        id: 3,
        categoriesId: 0,
        name: "Iphone 12 Pro",
        phoneTypesId: 0,
        colors: { name: "Xanh lá", value: "#a7ffeb" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/213032/iphone-12-pro-bac-new-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "IOS",
        salePrices: 3400,
        promotionPercents: 15,
        ram: "64GB",
        originalPrices: 4000,
      },
      {
        id: 4,
        categoriesId: 0,
        name: "Iphone 11",
        phoneTypesId: 0,
        colors: { name: "Tím", value: "#ce93d8" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/153856/iphone-xi-do-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "IOS",
        salePrices: 3400,
        promotionPercents: 15,
        ram: "64GB",
        originalPrices: 4000,
      },
      {
        id: 5,
        categoriesId: 0,
        name: "Iphone XR",
        phoneTypesId: 0,
        colors: { name: "Trắng", value: "#ffff" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/190325/iphone-xr-hopmoi-den-600x600-2-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "IOS",
        salePrices: 1200,
        promotionPercents: 0,
        ram: "64GB",
        originalPrices: 1200,
      },
      {
        id: 6,
        categoriesId: 0,
        name: "Iphone SE(2020) (Hộp mới)",
        phoneTypesId: 0,
        colors: { name: "Đen", value: "black" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/230410/iphone-se-2020-trang-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "IOS",
        salePrices: 1200,
        promotionPercents: 0,
        ram: "64GB",
        originalPrices: 1200,
      },
      {
        id: 7,
        categoriesId: 0,
        name: "xiao mi 11 lite",
        phoneTypesId: 1,
        colors: { name: "Đỏ", value: "#ef5350" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/233241/xiaomi-mi-11-lite-4g-blue-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        salePrices: 1170,
        promotionPercents: 10,
        ram: "64GB",
        originalPrices: 1300,
      },
      {
        id: 8,
        categoriesId: 0,
        name: "xiao mi poco x3 NFC",
        phoneTypesId: 1,
        colors: { name: "Xanh lá", value: "#a7ffeb" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/227900/xiaomi-poco-x3-nfc-xam-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "Android",
        salePrices: 720,
        promotionPercents: 20,
        ram: "64GB",
        originalPrices: 900,
      },
      {
        id: 9,
        categoriesId: 0,
        name: "xiao mi 10",
        phoneTypesId: 1,
        colors: { name: "Xanh lá", value: "#a7ffeb" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/246200/redmi-10-gray-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "Android",
        salePrices: 1170,
        promotionPercents: 10,
        ram: "64GB",
        originalPrices: 1300,
      },
      {
        id: 25,
        categoriesId: 0,
        name: "Samsung Galaxy Z Fold3 5G",
        phoneTypesId: 2,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/226935/samsung-galaxy-z-fold-3-silver-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        colors: { name: "Xanh lá", value: "#a7ffeb" },
        salePrices: 3400,
        promotionPercents: 15,
        ram: "64GB",
        originalPrices: 4000,
      },
      {
        id: 10,
        categoriesId: 0,
        name: "Samsung Galaxy A52 5G",
        phoneTypesId: 2,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/235440/samsung-galaxy-a52-5g-thumb-black-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        colors: { name: "Đen", value: "black" },
        salePrices: 1170,
        promotionPercents: 10,
        ram: "64GB",
        originalPrices: 1300,
      },
      {
        id: 11,
        categoriesId: 0,
        name: "Samsung Galaxy Z Flold2 5G",
        phoneTypesId: 2,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/226099/samsung-galaxy-z-fold-2-den-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        colors: { name: "Xanh lá", value: "#a7ffeb" },
        salePrices: 3400,
        promotionPercents: 15,
        ram: "64GB",
        originalPrices: 4000,
      },
      {
        id: 12,
        categoriesId: 0,
        name: "Samsung Galaxy Z Fold2 5G Đặc Biệt",
        phoneTypesId: 2,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/232668/samsung-galaxy-z-fold-2-den-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "Android",
        colors: { name: "Đỏ", value: "#ef5350" },
        salePrices: 1170,
        promotionPercents: 10,
        ram: "64GB",
        originalPrices: 1300,
      },
      {
        id: 13,
        categoriesId: 0,
        name: "Samsung Galaxy Z Fold3 5G",
        phoneTypesId: 2,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/248284/samsung-galaxy-z-fold-3-black-1-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "Android",
        colors: { name: "Trắng", value: "#ffff" },
        salePrices: 3400,
        promotionPercents: 15,
        ram: "64GB",
        originalPrices: 4000,
      },
      {
        id: 14,
        categoriesId: 0,
        name: "Oppo Reno6 Z 5G",
        phoneTypesId: 3,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/239747/oppo-reno6-z-5g-aurora-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "Android",
        colors: { name: "Đen", value: "black" },
        salePrices: 1170,
        promotionPercents: 10,
        ram: "64GB",
        originalPrices: 1300,
      },
      {
        id: 15,
        categoriesId: 0,
        name: "Oppo Reno5 Marvel",
        phoneTypesId: 3,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/236024/oppo-reno5-marvel-thumb-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        colors: { name: "Xanh lá", value: "#a7ffeb" },
        salePrices: 3400,
        promotionPercents: 15,
        ram: "64GB",
        originalPrices: 4000,
      },
      {
        id: 16,
        categoriesId: 0,
        name: "Oppo A15s",
        phoneTypesId: 3,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/229948/oppo-a15s-xanh-600x600-3-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        colors: { name: "Trắng", value: "#ffff" },
        salePrices: 1170,
        promotionPercents: 10,
        ram: "64GB",
        originalPrices: 1300,
      },
      {
        id: 17,
        categoriesId: 0,
        name: "Oppo Find X3 Pro 5G",
        phoneTypesId: 3,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/232190/oppo-find-x3-pro-black-001-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "Android",
        colors: { name: "Đỏ", value: "#ef5350" },
        salePrices: 720,
        promotionPercents: 20,
        ram: "64GB",
        originalPrices: 900,
      },
      {
        id: 18,
        categoriesId: 0,
        name: "Vivo Y72 5G",
        phoneTypesId: 4,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/236431/vivo-y72-5g-blue-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "Android",
        colors: { name: "Đen", value: "black" },
        salePrices: 3400,
        promotionPercents: 15,
        ram: "64GB",
        originalPrices: 4000,
      },
      {
        id: 24,
        categoriesId: 0,
        name: "Vivo Y53s",
        phoneTypesId: 4,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/240286/vivo-y53s-xanh-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "Android",
        colors: { name: "Trắng", value: "#ffff" },
        salePrices: 3400,
        promotionPercents: 15,
        ram: "64GB",
        originalPrices: 4000,
      },
      {
        id: 19,
        categoriesId: 0,
        name: "Vivo Y11",
        phoneTypesId: 4,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/212357/vivo-y11-600-600-do-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "Android",
        colors: { name: "Đỏ", value: "#ef5350" },
        salePrices: 3400,
        promotionPercents: 15,
        ram: "64GB",
        originalPrices: 4000,
      },
      {
        id: 20,
        categoriesId: 0,
        name: "Vivo Y1s",
        phoneTypesId: 4,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/225851/vivo-y1s-xanh-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "Android",
        colors: { name: "Xanh dương", value: "#64b5f6" },
        salePrices: 3400,
        promotionPercents: 15,
        ram: "64GB",
        originalPrices: 4000,
      },
      {
        id: 21,
        categoriesId: 0,
        name: "Vivo Y20",
        phoneTypesId: 4,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/227525/vivo-y20-white-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "Android",
        colors: { name: "Xanh lá", value: "#a7ffeb" },
        salePrices: 1200,
        promotionPercents: 0,
        ram: "64GB",
        originalPrices: 1200,
      },
      {
        id: 24,
        categoriesId: 0,
        name: "Iphone 12",
        phoneTypesId: 0,
        colors: { name: "Trắng", value: "#ffff" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/213031/iphone-12-violet-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "IOS",
        salePrices: 1400,
        promotionPercents: 0,
        ram: "128GB",
        originalPrices: 1400,
      },
      {
        id: 25,
        categoriesId: 0,
        name: "Iphone 12",
        phoneTypesId: 0,
        colors: { name: "Trắng", value: "#ffff" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/213031/iphone-12-violet-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "IOS",
        salePrices: 1530,
        promotionPercents: 10,
        ram: "256GB",
        originalPrices: 1700,
      },
      {
        id: 26,
        categoriesId: 0,
        name: "Iphone 12",
        phoneTypesId: 0,
        colors: { name: "Tím", value: "#ce93d8" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/213031/iphone-12-violet-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "IOS",
        salePrices: 1200,
        promotionPercents: 20,
        ram: "512GB",
        originalPrices: 1500,
      },
      {
        id: 27,
        categoriesId: 0,
        name: "Iphone 12 Pro Max",
        phoneTypesId: 0,
        colors: { name: "Tím", value: "#ce93d8" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-xanh-duong-new-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "IOS",
        salePrices: 880,
        promotionPercents: 20,
        ram: "128GB",
        originalPrices: 1100,
      },
      {
        id: 28,
        categoriesId: 0,
        name: "Iphone 12 Pro Max",
        phoneTypesId: 0,
        colors: { name: "Đen", value: "black" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-xanh-duong-new-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "IOS",
        salePrices: 1600,
        promotionPercents: 0,
        ram: "256GB",
        originalPrices: 1600,
      },
      {
        id: 29,
        categoriesId: 0,
        name: "Iphone 12 Pro Max",
        phoneTypesId: 0,
        colors: { name: "Trắng", value: "#ffff" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-xanh-duong-new-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "IOS",
        salePrices: 3910,
        promotionPercents: 15,
        ram: "512GB",
        originalPrices: 4600,
      },
      {
        id: 30,
        categoriesId: 0,
        name: "Iphone 12 Pro",
        phoneTypesId: 0,
        colors: { name: "Xanh dương", value: "#64b5f6" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/213032/iphone-12-pro-bac-new-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "IOS",
        salePrices: 880,
        promotionPercents: 20,
        ram: "128GB",
        originalPrices: 1100,
      },
      {
        id: 31,
        categoriesId: 0,
        name: "Iphone 12 Pro",
        phoneTypesId: 0,
        colors: { name: "Trắng", value: "#ffff" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/213032/iphone-12-pro-bac-new-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "IOS",
        salePrices: 3740,
        promotionPercents: 15,
        ram: "256GB",
        originalPrices: 4400,
      },
      {
        id: 32,
        categoriesId: 0,
        name: "Iphone 12 Pro",
        phoneTypesId: 0,
        colors: { name: "Xanh dương", value: "#64b5f6" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/213032/iphone-12-pro-bac-new-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "IOS",
        salePrices: 1200,
        promotionPercents: 20,
        ram: "512GB",
        originalPrices: 1500,
      },
      {
        id: 33,
        categoriesId: 0,
        name: "Iphone 11",
        phoneTypesId: 0,
        colors: { name: "Đỏ", value: "#ef5350" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/153856/iphone-xi-do-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "IOS",
        salePrices: 1350,
        promotionPercents: 10,
        ram: "128GB",
        originalPrices: 1500,
      },
      {
        id: 34,
        categoriesId: 0,
        name: "Iphone 11",
        phoneTypesId: 0,
        colors: { name: "Xanh lá", value: "#a7ffeb" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/153856/iphone-xi-do-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "IOS",
        salePrices: 1600,
        promotionPercents: 0,
        ram: "256GB",
        originalPrices: 1600,
      },
      {
        id: 35,
        categoriesId: 0,
        name: "Iphone 11",
        phoneTypesId: 0,
        colors: { name: "Đỏ", value: "#ef5350" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/153856/iphone-xi-do-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "IOS",
        salePrices: 1200,
        promotionPercents: 20,
        ram: "512GB",
        originalPrices: 1500,
      },
      {
        id: 36,
        categoriesId: 0,
        name: "Iphone XR",
        phoneTypesId: 0,
        colors: { name: "Đỏ", value: "#ef5350" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/190325/iphone-xr-hopmoi-den-600x600-2-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "IOS",
        salePrices: 1350,
        promotionPercents: 10,
        ram: "128GB",
        originalPrices: 1500,
      },
      {
        id: 37,
        categoriesId: 0,
        name: "Iphone XR",
        phoneTypesId: 0,
        colors: { name: "Đen", value: "black" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/190325/iphone-xr-hopmoi-den-600x600-2-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "IOS",
        salePrices: 3740,
        promotionPercents: 15,
        ram: "256GB",
        originalPrices: 4400,
      },
      {
        id: 38,
        categoriesId: 0,
        name: "Iphone XR",
        phoneTypesId: 0,
        colors: { name: "Đen", value: "black" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/190325/iphone-xr-hopmoi-den-600x600-2-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "IOS",
        salePrices: 1710,
        promotionPercents: 10,
        ram: "512GB",
        originalPrices: 1900,
      },
      {
        id: 39,
        categoriesId: 0,
        name: "Iphone SE(2020) (Hộp mới)",
        phoneTypesId: 0,
        colors: { name: "Xanh dương", value: "#64b5f6" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/230410/iphone-se-2020-trang-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "IOS",
        salePrices: 3570,
        promotionPercents: 15,
        ram: "128GB",
        originalPrices: 4200,
      },
      {
        id: 40,
        categoriesId: 0,
        name: "Iphone SE(2020) (Hộp mới)",
        phoneTypesId: 0,
        colors: { name: "Đỏ", value: "#ef5350" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/230410/iphone-se-2020-trang-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "IOS",
        salePrices: 1040,
        promotionPercents: 20,
        ram: "256GB",
        originalPrices: 1300,
      },
      {
        id: 41,
        categoriesId: 0,
        name: "Iphone SE(2020) (Hộp mới)",
        phoneTypesId: 0,
        colors: { name: "Xanh dương", value: "#64b5f6" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/230410/iphone-se-2020-trang-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "IOS",
        salePrices: 3910,
        promotionPercents: 15,
        ram: "512GB",
        originalPrices: 4600,
      },
      {
        id: 42,
        categoriesId: 0,
        name: "xiao mi 11 lite",
        phoneTypesId: 1,
        colors: { name: "Xanh lá", value: "#a7ffeb" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/233241/xiaomi-mi-11-lite-4g-blue-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        salePrices: 1400,
        promotionPercents: 0,
        ram: "128GB",
        originalPrices: 1400,
      },
      {
        id: 43,
        categoriesId: 0,
        name: "xiao mi 11 lite",
        phoneTypesId: 1,
        colors: { name: "Xanh dương", value: "#64b5f6" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/233241/xiaomi-mi-11-lite-4g-blue-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        salePrices: 1530,
        promotionPercents: 10,
        ram: "256GB",
        originalPrices: 1700,
      },
      {
        id: 44,
        categoriesId: 0,
        name: "xiao mi 11 lite",
        phoneTypesId: 1,
        colors: { name: "Trắng", value: "#ffff" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/233241/xiaomi-mi-11-lite-4g-blue-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        salePrices: 1800,
        promotionPercents: 0,
        ram: "512GB",
        originalPrices: 1800,
      },
      {
        id: 45,
        categoriesId: 0,
        name: "xiao mi poco x3 NFC",
        phoneTypesId: 1,
        colors: { name: "Tím", value: "#ce93d8" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/227900/xiaomi-poco-x3-nfc-xam-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "Android",
        salePrices: 880,
        promotionPercents: 20,
        ram: "128GB",
        originalPrices: 1100,
      },
      {
        id: 46,
        categoriesId: 0,
        name: "xiao mi poco x3 NFC",
        phoneTypesId: 1,
        colors: { name: "Xanh lá", value: "#a7ffeb" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/227900/xiaomi-poco-x3-nfc-xam-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "Android",
        salePrices: 1040,
        promotionPercents: 20,
        ram: "256GB",
        originalPrices: 1300,
      },
      {
        id: 47,
        categoriesId: 0,
        name: "xiao mi poco x3 NFC",
        phoneTypesId: 1,
        colors: { name: "Đen", value: "black" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/227900/xiaomi-poco-x3-nfc-xam-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "Android",
        salePrices: 3910,
        promotionPercents: 15,
        ram: "512GB",
        originalPrices: 4600,
      },
      {
        id: 48,
        categoriesId: 0,
        name: "xiao mi 10",
        phoneTypesId: 1,
        colors: { name: "Tím", value: "#ce93d8" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/246200/redmi-10-gray-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "Android",
        salePrices: 1400,
        promotionPercents: 0,
        ram: "128GB",
        originalPrices: 1400,
      },
      {
        id: 49,
        categoriesId: 0,
        name: "xiao mi 10",
        phoneTypesId: 1,
        colors: { name: "Đen", value: "black" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/246200/redmi-10-gray-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "Android",
        salePrices: 1530,
        promotionPercents: 10,
        ram: "256GB",
        originalPrices: 1700,
      },
      {
        id: 50,
        categoriesId: 0,
        name: "xiao mi 10",
        phoneTypesId: 1,
        colors: { name: "Trắng", value: "#ffff" },
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/246200/redmi-10-gray-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "Android",
        salePrices: 3910,
        promotionPercents: 15,
        ram: "512GB",
        originalPrices: 4600,
      },
      {
        id: 51,
        categoriesId: 0,
        name: "Samsung Galaxy Z Fold3 5G",
        phoneTypesId: 2,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/226935/samsung-galaxy-z-fold-3-silver-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        colors: { name: "Xanh dương", value: "#64b5f6" },
        salePrices: 1400,
        promotionPercents: 0,
        ram: "128GB",
        originalPrices: 1400,
      },
      {
        id: 52,
        categoriesId: 0,
        name: "Samsung Galaxy Z Fold3 5G",
        phoneTypesId: 2,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/226935/samsung-galaxy-z-fold-3-silver-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        colors: { name: "Đỏ", value: "#ef5350" },
        salePrices: 1710,
        promotionPercents: 10,
        ram: "512GB",
        originalPrices: 1900,
      },
      {
        id: 53,
        categoriesId: 0,
        name: "Samsung Galaxy A52 5G",
        phoneTypesId: 2,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/235440/samsung-galaxy-a52-5g-thumb-black-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        colors: { name: "Tím", value: "#ce93d8" },
        salePrices: 3570,
        promotionPercents: 15,
        ram: "128GB",
        originalPrices: 4200,
      },
      {
        id: 54,
        categoriesId: 0,
        name: "Samsung Galaxy A52 5G",
        phoneTypesId: 2,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/235440/samsung-galaxy-a52-5g-thumb-black-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        colors: { name: "Tím", value: "#ce93d8" },
        salePrices: 1200,
        promotionPercents: 20,
        ram: "512GB",
        originalPrices: 1500,
      },
      {
        id: 55,
        categoriesId: 0,
        name: "Samsung Galaxy Z Flold2 5G",
        phoneTypesId: 2,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/226099/samsung-galaxy-z-fold-2-den-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        colors: { name: "Trắng", value: "#ffff" },
        salePrices: 1350,
        promotionPercents: 10,
        ram: "128GB",
        originalPrices: 1500,
      },
      {
        id: 56,
        categoriesId: 0,
        name: "Samsung Galaxy Z Flold2 5G",
        phoneTypesId: 2,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/226099/samsung-galaxy-z-fold-2-den-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        colors: { name: "Xanh lá", value: "#a7ffeb" },
        salePrices: 1200,
        promotionPercents: 20,
        ram: "512GB",
        originalPrices: 1500,
      },
      {
        id: 57,
        categoriesId: 0,
        name: "Samsung Galaxy Z Fold2 5G Đặc Biệt",
        phoneTypesId: 2,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/232668/samsung-galaxy-z-fold-2-den-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "Android",
        colors: { name: "Xanh dương", value: "#64b5f6" },
        salePrices: 1400,
        promotionPercents: 0,
        ram: "128GB",
        originalPrices: 1400,
      },
      {
        id: 58,
        categoriesId: 0,
        name: "Samsung Galaxy Z Fold2 5G Đặc Biệt",
        phoneTypesId: 2,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/232668/samsung-galaxy-z-fold-2-den-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "Android",
        colors: { name: "Tím", value: "#ce93d8" },
        salePrices: 3910,
        promotionPercents: 15,
        ram: "512GB",
        originalPrices: 4600,
      },
      {
        id: 59,
        categoriesId: 0,
        name: "Samsung Galaxy Z Fold3 5G",
        phoneTypesId: 2,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/248284/samsung-galaxy-z-fold-3-black-1-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "Android",
        colors: { name: "Đen", value: "black" },
        salePrices: 1400,
        promotionPercents: 0,
        ram: "128GB",
        originalPrices: 1400,
      },
      {
        id: 60,
        categoriesId: 0,
        name: "Samsung Galaxy Z Fold3 5G",
        phoneTypesId: 2,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/248284/samsung-galaxy-z-fold-3-black-1-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "Android",
        colors: { name: "Đen", value: "black" },
        salePrices: 1200,
        promotionPercents: 20,
        ram: "512GB",
        originalPrices: 1500,
      },
      {
        id: 61,
        categoriesId: 0,
        name: "Oppo Reno6 Z 5G",
        phoneTypesId: 3,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/239747/oppo-reno6-z-5g-aurora-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "Android",
        colors: { name: "Đỏ", value: "#ef5350" },
        salePrices: 880,
        promotionPercents: 20,
        ram: "128GB",
        originalPrices: 1100,
      },
      {
        id: 62,
        categoriesId: 0,
        name: "Oppo Reno6 Z 5G",
        phoneTypesId: 3,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/239747/oppo-reno6-z-5g-aurora-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "Android",
        colors: { name: "Đỏ", value: "#ef5350" },
        salePrices: 1800,
        promotionPercents: 0,
        ram: "512GB",
        originalPrices: 1800,
      },
      {
        id: 63,
        categoriesId: 0,
        name: "Oppo Reno5 Marvel",
        phoneTypesId: 3,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/236024/oppo-reno5-marvel-thumb-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        colors: { name: "Đỏ", value: "#ef5350" },
        salePrices: 1400,
        promotionPercents: 0,
        ram: "128GB",
        originalPrices: 1400,
      },
      {
        id: 64,
        categoriesId: 0,
        name: "Oppo Reno5 Marvel",
        phoneTypesId: 3,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/236024/oppo-reno5-marvel-thumb-600x600-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        colors: { name: "Xanh lá", value: "#a7ffeb" },
        salePrices: 1800,
        promotionPercents: 0,
        ram: "512GB",
        originalPrices: 1800,
      },
      {
        id: 65,
        categoriesId: 0,
        name: "Oppo A15s",
        phoneTypesId: 3,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/229948/oppo-a15s-xanh-600x600-3-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        colors: { name: "Tím", value: "#ce93d8" },
        salePrices: 880,
        promotionPercents: 20,
        ram: "128GB",
        originalPrices: 1100,
      },
      {
        id: 66,
        categoriesId: 0,
        name: "Oppo A15s",
        phoneTypesId: 3,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/229948/oppo-a15s-xanh-600x600-3-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 2000,
        osTypes: "Android",
        colors: { name: "Đen", value: "black" },
        salePrices: 1200,
        promotionPercents: 20,
        ram: "512GB",
        originalPrices: 1500,
      },
      {
        id: 67,
        categoriesId: 0,
        name: "Oppo Find X3 Pro 5G",
        phoneTypesId: 3,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/232190/oppo-find-x3-pro-black-001-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "Android",
        colors: { name: "Xanh lá", value: "#a7ffeb" },
        salePrices: 880,
        promotionPercents: 20,
        ram: "128GB",
        originalPrices: 1100,
      },
      {
        id: 68,
        categoriesId: 0,
        name: "Oppo Find X3 Pro 5G",
        phoneTypesId: 3,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/232190/oppo-find-x3-pro-black-001-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "Android",
        colors: { name: "Đen", value: "black" },
        salePrices: 1710,
        promotionPercents: 10,
        ram: "512GB",
        originalPrices: 1900,
      },
      {
        id: 69,
        categoriesId: 0,
        name: "Vivo Y72 5G",
        phoneTypesId: 4,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/236431/vivo-y72-5g-blue-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "Android",
        colors: { name: "Trắng", value: "#ffff" },
        salePrices: 3570,
        promotionPercents: 15,
        ram: "128GB",
        originalPrices: 4200,
      },
      {
        id: 70,
        categoriesId: 0,
        name: "Vivo Y72 5G",
        phoneTypesId: 4,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/236431/vivo-y72-5g-blue-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "Android",
        colors: { name: "Xanh dương", value: "#64b5f6" },
        salePrices: 3910,
        promotionPercents: 15,
        ram: "512GB",
        originalPrices: 4600,
      },
      {
        id: 71,
        categoriesId: 0,
        name: "Vivo Y53s",
        phoneTypesId: 4,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/240286/vivo-y53s-xanh-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "Android",
        colors: { name: "Tím", value: "#ce93d8" },
        salePrices: 3570,
        promotionPercents: 15,
        ram: "128GB",
        originalPrices: 4200,
      },
      {
        id: 72,
        categoriesId: 0,
        name: "Vivo Y53s",
        phoneTypesId: 4,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/240286/vivo-y53s-xanh-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "Android",
        colors: { name: "Đen", value: "black" },
        salePrices: 1800,
        promotionPercents: 0,
        ram: "512GB",
        originalPrices: 1800,
      },
      {
        id: 73,
        categoriesId: 0,
        name: "Vivo Y11",
        phoneTypesId: 4,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/212357/vivo-y11-600-600-do-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "Android",
        colors: { name: "Đỏ", value: "#ef5350" },
        salePrices: 3570,
        promotionPercents: 15,
        ram: "128GB",
        originalPrices: 4200,
      },
      {
        id: 74,
        categoriesId: 0,
        name: "Vivo Y11",
        phoneTypesId: 4,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/212357/vivo-y11-600-600-do-1-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 5000,
        osTypes: "Android",
        colors: { name: "Đỏ", value: "#ef5350" },
        salePrices: 1200,
        promotionPercents: 20,
        ram: "512GB",
        originalPrices: 1500,
      },
      {
        id: 75,
        categoriesId: 0,
        name: "Vivo Y1s",
        phoneTypesId: 4,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/225851/vivo-y1s-xanh-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "Android",
        colors: { name: "Tím", value: "#ce93d8" },
        salePrices: 1400,
        promotionPercents: 0,
        ram: "128GB",
        originalPrices: 1400,
      },
      {
        id: 76,
        categoriesId: 0,
        name: "Vivo Y1s",
        phoneTypesId: 4,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/225851/vivo-y1s-xanh-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "Android",
        colors: { name: "Trắng", value: "#ffff" },
        salePrices: 1710,
        promotionPercents: 10,
        ram: "512GB",
        originalPrices: 1900,
      },
      {
        id: 77,
        categoriesId: 0,
        name: "Vivo Y20",
        phoneTypesId: 4,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/227525/vivo-y20-white-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "Android",
        colors: { name: "Tím", value: "#ce93d8" },
        salePrices: 880,
        promotionPercents: 20,
        ram: "128GB",
        originalPrices: 1100,
      },
      {
        id: 78,
        categoriesId: 0,
        name: "Vivo Y20",
        phoneTypesId: 4,
        color: ["white"],
        imageUrl: [
          "https://cdn.tgdd.vn/Products/Images/42/227525/vivo-y20-white-600x600.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-1-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-2-org.jpg",
          "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-3-org.jpg",
        ],
        batteries: 1500,
        osTypes: "Android",
        colors: { name: "Đen", value: "black" },
        salePrices: 3910,
        promotionPercents: 15,
        ram: "512GB",
        originalPrices: 4600,
      },
    ],
  };

  rams = ["4GB", "6GB", "8GB", "12GB", "16GB"];
  const randomRam = () => {
    const index = Math.trunc(Math.random() * rams.length);
    return rams[index];
  };

  db.products.forEach((p, i) => {
    db.products[i].rom = p.ram;
    db.products[i].ram = randomRam();
  });

  // Write db Object to db.json file
  fs.writeFile("./db.json", JSON.stringify(db), successfullCallback);

  function successfullCallback() {
    console.log("Generate data successfully");
  }
})();
