@baseUrl=http://localhost:8000
@resourceName=products

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###
# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?categoriesId=0
###
GET {{baseUrl}}/{{resourceName}}?salePrices_lte=1500
###
GET {{baseUrl}}/{{resourceName}}?name_like=iphone

###
# @name pagination
GET {{baseUrl}}/{{resourceName}}?_limit=39&_page=1

###
GET {{baseUrl}}/{{resourceName}}?_order=desc&_sort=salePrices&categoriesId=0

###
GET {{baseUrl}}/{{resourceName}}?_order=asc&_sort=rams.64GB.salePrices

###
GET {{baseUrl}}/{{resourceName}}?_sort=color,price&order=asc,desc


###

# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "categoryId": "b17fcec8-5777-4c92-a879-e518d747c5a9",
    "name": "Le Thanh Tong",
    "color": "lavender",
    "price": 663,
    "description": "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
    "thumbnailUrl": "http://placeimg.com/400/400"
}

###

# @name update
PATCH {{baseUrl}}/{{resourceName}}/wMgNTBq
Content-Type: application/json

{
    "name": "New laptop le thanh tong",
    "price": 663
}